@hostname = localhost
@port = 8080
@host = {{hostname}}:{{port}}
@contentType = application/json
@jwtToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTU5MjUzMjgsImlzcyI6ImNvbS50ZWxsYXcuYmFuayIsInN1YiI6IjgzNTZmZmZhLTc2Y2QtNGU1My1iNzMzLTc0YTE5M2I5MWRjOCJ9.M9wEHkqK9qbKJH7j4y3T-4S9W4uA-CTMkc0F53je6qA
@walletId = 28b68ddd-8daa-4585-9e0d-d535b3f379ed

###

### Health Check
GET http://{{host}}/health

###

### Sign Up - Create new user
POST http://{{host}}/sign-up
Content-Type: {{contentType}}

{
  "first_name": "John",
  "last_name": "Moe",
  "email": "john.moe@example.com",
  "password": "password123"
}

###

### Sign In - Authenticate user
POST http://{{host}}/sign-in
Content-Type: {{contentType}}

{
  "email": "john.doe@example.com",
  "password": "password123"
}

###

### Create Wallet (requires authentication)
POST http://{{host}}/wallets
Content-Type: {{contentType}}
Authorization: Bearer {{jwtToken}}

{
  "name": "My Personal Wallet"
}

###

### List Wallets (requires authentication)
GET http://{{host}}/wallets
Content-Type: {{contentType}}
Authorization: Bearer {{jwtToken}}

###

### Share Wallet (requires authentication)
POST http://{{host}}/wallets/{{walletId}}/share
Content-Type: {{contentType}}
Authorization: Bearer {{jwtToken}}

{
  "user_email": "john.doe@example.com"
}

###

### Register Transaction (requires authentication)
POST http://{{host}}/wallets/{{walletId}}/transactions
Content-Type: {{contentType}}
Authorization: Bearer {{jwtToken}}

{
  "amount": 10000,
  "transaction_type": "withdraw"
}

###

### List Categories (requires categories)
GET http://{{host}}/wallets/{{walletId}}/categories
Content-Type: {{contentType}}
Authorization: Bearer {{jwtToken}}
