@host = https://wallet.k8s.lopesgabriel.dev
@contentType = application/json
@jwtToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzExMTg1NDQsImlhdCI6MTc3MTAzMjE0NCwic3ViIjoiYjhiYThlNDQtOTc0NC00YmJjLTgyNTAtYWQzYmY4Njc4ZjViIn0.lMYkUKXBzLwK-gTmI_WRMEBDT79kKS548__vidGGTkw
@walletId = 9ea5fa96-8989-48fb-867b-c3a8891a9b28

###

### Health Check
GET {{host}}/health

###

### Create Wallet (requires authentication)
POST {{host}}/wallets
Content-Type: {{contentType}}
Authorization: Bearer {{jwtToken}}

{
  "name": "Chá de casa nova"
}

###

### List Wallets (requires authentication)
GET {{host}}/wallets
Content-Type: {{contentType}}
Authorization: Bearer {{jwtToken}}

###

### Share Wallet (requires authentication)
POST {{host}}/wallets/{{walletId}}/share
Content-Type: {{contentType}}
Authorization: Bearer {{jwtToken}}

{
  "user_email": "john.doe@example.com"
}

###

### Register Transaction (requires authentication)
POST {{host}}/wallets/{{walletId}}/transactions
Content-Type: {{contentType}}
Authorization: Bearer {{jwtToken}}

{
  "amount": 10000,
  "transaction_type": "deposit",
  "description": "Guardando dinheiro para comprar um novo celular"
}
