@hostname = localhost
@port = 8080
@host = {{hostname}}:{{port}}
@contentType = application/json
@jwtToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTc1NjI2NjUsImlzcyI6ImNvbS50ZWxsYXcuYmFuayIsInN1YiI6Ijg4OTUyOGZiLWY0YWEtNDE1MS05YjRmLWM0ODM4NjQ1MDJjNSJ9.jf44HluvskgI2QQ4ptpiU9ED6TUXwXjdivtkvSveW98
@walletId = 09e4f61a-955c-449b-a7c5-14ed243e7fe2

###

### Health Check
GET http://{{host}}/health

###

### Sign Up - Create new user
POST http://{{host}}/sign-up
Content-Type: {{contentType}}

{
  "first_name": "John",
  "last_name": "Doe",
  "email": "john.doe@example.com",
  "password": "password123"
}

###

### Sign In - Authenticate user
POST http://{{host}}/sign-in
Content-Type: {{contentType}}

{
  "email": "john.doe@example.com",
  "password": "password123"
}

###

### Create Wallet (requires authentication)
POST http://{{host}}/wallets
Content-Type: {{contentType}}
Authorization: Bearer {{jwtToken}}

{
  "name": "My Personal Wallet"
}

###

### List Wallets (requires authentication)
GET http://{{host}}/wallets
Content-Type: {{contentType}}
Authorization: Bearer {{jwtToken}}

###

### Share Wallet (requires authentication)
POST http://{{host}}/wallets/{{walletId}}/share
Content-Type: {{contentType}}
Authorization: Bearer {{jwtToken}}

{
  "user_email": "john.doe@example.com"
}

###

### Register Transaction (requires authentication)
POST http://{{host}}/wallets/{{walletId}}/transactions
Content-Type: {{contentType}}
Authorization: Bearer {{jwtToken}}

{
  "amount": 24000,
  "transaction_type": "withdraw",
  "description": "September Consortium"
}
