@hostname = localhost
@port = 8080
@host = {{hostname}}:{{port}}
@contentType = application/json
@jwtToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTc1NjQ4MzYsImlzcyI6ImNvbS50ZWxsYXcuYmFuayIsInN1YiI6Ijg4OTUyOGZiLWY0YWEtNDE1MS05YjRmLWM0ODM4NjQ1MDJjNSJ9.KIoojnjFDPGAjCpNxlfOGQaGEy8MeWua0sudXQZsF8Q
@walletId = 9ea5fa96-8989-48fb-867b-c3a8891a9b28

###

### Health Check
GET http://{{host}}/health

###

### Sign Up - Create new user
POST http://{{host}}/sign-up
Content-Type: {{contentType}}

{
  "first_name": "John",
  "last_name": "Doe",
  "email": "john.doe@example.com",
  "password": "password123"
}

###

### Sign In - Authenticate user
POST http://{{host}}/sign-in
Content-Type: {{contentType}}

{
  "email": "john.doe@example.com",
  "password": "password123"
}

###

### Create Wallet (requires authentication)
POST http://{{host}}/wallets
Content-Type: {{contentType}}
Authorization: Bearer {{jwtToken}}

{
  "name": "My Personal Wallet"
}

###

### List Wallets (requires authentication)
GET http://{{host}}/wallets
Content-Type: {{contentType}}
Authorization: Bearer {{jwtToken}}

###

### Share Wallet (requires authentication)
POST http://{{host}}/wallets/{{walletId}}/share
Content-Type: {{contentType}}
Authorization: Bearer {{jwtToken}}

{
  "user_email": "john.doe@example.com"
}

###

### Register Transaction (requires authentication)
POST http://{{host}}/wallets/{{walletId}}/transactions
Content-Type: {{contentType}}
Authorization: Bearer {{jwtToken}}

{
  "amount": 14000,
  "transaction_type": "deposit",
  "description": "Academia Indi"
}
